{
 "title": "TrackerManager DataMining",
 "time": { "from": "now-10m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Page count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(1) as \"count\"\nFROM\n  processing_progress\n"
    }
   ]
  },
  {
   "title": "Processing progress",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  progress AS \"progress\",\n  count(progress) AS \"count\"\nFROM processing_progress\nGROUP BY run_id, progress\nORDER BY run_id, progress"
    }
   ]
  },
  {
   "title": "Queued",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 14, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH total as (\n  SELECT count(1) as \"total_count\" from processing_progress\n)\nSELECT\n  count(1) / (SELECT COALESCE(NULLIF(total_count, 0), 1) FROM total)::float * 100 as \"percentage\"\nFROM\n  processing_progress\nwhere\n  progress = 'queued'\n"
    }
   ]
  },
  {
   "title": "Saved",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 14, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH total as (\n  SELECT count(1) as \"total_count\" from processing_progress\n)\nSELECT\n  count(1) / (SELECT COALESCE(NULLIF(total_count, 0), 1) FROM total)::float * 100 as \"percentage\"\nFROM\n  processing_progress\nwhere\n  progress = 'saved'\n"
    }
   ]
  },
  { "title": "HTML Producer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Count of page loads",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "measurement": "htmlparser.exec_time.load_page",
     "query": "SELECT count(\"value\") FROM \"load_page\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Page load / minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "htmlparser.exec_time.load_page",
     "query": "SELECT count(\"value\") FROM \"htmlproducer.exec_time.load_page\" WHERE $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Count of parsed HTMLs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "htmlparser.exec_time.parse",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Page load time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_hostname",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "htmlparser.exec_time.load_page",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Count of parsed torrent items",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "htmlparser.torrentitems_count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HTML parsing time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_hostname",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" }
     ],
     "measurement": "htmlparser.exec_time.parse",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "DB add execution time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "htmlparser.exec_time.db_add",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "htmlparser.exec_time.produce",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  }
 ]
}