version: "3.7"
services:
  replicator:
    image: MyCloudPR4100:5000/trackermanager/replicator
    container_name: replicator
    ports:
      - "10001:80"
    environment:
      CsvFilePath: "/var/lib/shared-infra/sharedfile.csv"
      Postgres__ConnectionString: "Host=postgres;Username=dbuser;Password=password123;Database=datamining"
      MongoDB__ConnectionString: "mongodb://root:mypassword@mongodb:27017/?authSource=admin&readPreference=primary&ssl=false"
    volumes:
      - "shared-infra-volume:/var/lib/shared-infra"

networks:
  default:
    external: true
    name: shared-infra-network

volumes:
  shared-infra-volume:
    external: true
