version: "3.7"
services: 
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

networks:
  default:
    external: true
    name: shared-infra-network