version: "3.7"
services: 
  grafana:
    image: grafana/grafana-oss:8.2.1-ubuntu
    container_name: grafana
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
  grafana-storage:

networks:
  default:
    external: true
    name: shared-infra-network